# Generated by Django 5.1.7 on 2025-03-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.PositiveIntegerField()),
                ('tipo', models.CharField(max_length=30)),
                ('numero_puertas', models.PositiveIntegerField()),
                ('capacidad_pasajeros', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=30)),
                ('fecha_incorporacion', models.DateField(auto_now_add=True)),
                ('tipo_combustible', models.CharField(max_length=20)),
                ('transmision', models.CharField(max_length=20)),
                ('kilometraje', models.PositiveIntegerField()),
                ('potencia_motor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('consumo_combustible', models.DecimalField(decimal_places=2, max_digits=4)),
                ('capacidad_maletero', models.PositiveIntegerField()),
                ('precio_alquiler_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposito_seguridad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(max_length=100)),
                ('fecha_ultima_renta', models.DateField(blank=True, null=True)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('vin', models.CharField(max_length=20, unique=True)),
                ('seguro_vigente', models.BooleanField(default=True)),
                ('fecha_vencimiento_seguro', models.DateField(blank=True, null=True)),
                ('estado_documentacion', models.CharField(max_length=100)),
                ('historial_mantenimientos', models.TextField()),
                ('ultima_inspeccion', models.DateField(blank=True, null=True)),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('historial_accidentes', models.TextField()),
                ('valor_actual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fotos', models.JSONField()),
                ('descripcion_adicional', models.TextField()),
            ],
        ),
    ]
