# Generated by Django 5.1.7 on 2025-03-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_alter_vehiculo_descripcion_adicional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(choices=[('blanco', 'Blanco'), ('negro', 'Negro'), ('gris', 'Gris'), ('rojo', 'Rojo'), ('azul', 'Azul'), ('plateado', 'Plateado'), ('verde', 'Verde'), ('amarillo', 'Amarillo'), ('marron', 'Marrón'), ('naranja', 'Naranja'), ('beige', 'Beige'), ('violeta', 'Violeta'), ('turquesa', 'Turquesa')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('rentado', 'Rentado'), ('en_mantenimiento', 'En mantenimiento'), ('inactivo', 'Inactivo'), ('reservado', 'Reservado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='estado_documentacion',
            field=models.CharField(choices=[('completa', 'Completa'), ('pendiente', 'Pendiente'), ('vencida', 'Vencida'), ('incompleta', 'Incompleta')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('sedan', 'Sedán'), ('coupe', 'Coupé'), ('convertible', 'Convertible'), ('hatchback', 'Hatchback'), ('suv', 'SUV'), ('pickup', 'Pickup'), ('hibrido', 'Híbrido'), ('crossover', 'Crossover'), ('deportivo', 'Deportivo'), ('minivan', 'Minivan'), ('station_wagon', 'Station Wagon'), ('electrico', 'Eléctrico'), ('todo_terreno', 'Todo Terreno'), ('furgoneta', 'Furgoneta'), ('superdeportivo', 'Superdeportivo'), ('microcar', 'Microcar'), ('roadster', 'Roadster'), ('muscle_car', 'Muscle Car'), ('limusina', 'Limusina'), ('vehiculo_comercial', 'Vehículo Comercial'), ('cabriolet', 'Cabriolet'), ('offroad', 'Offroad')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_combustible',
            field=models.CharField(choices=[('gasolina', 'Gasolina'), ('diesel', 'Diésel'), ('hibrido', 'Híbrido'), ('electrico', 'Eléctrico'), ('gas_gnv_glp', 'Gas (GNV/GLP)'), ('etanol', 'Etanol'), ('biodiesel', 'Biodiesel')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='transmision',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatica', 'Automática'), ('cvt', 'CVT'), ('semi_automatica', 'Semi-Automática'), ('tiptronic', 'Tiptronic'), ('dual_clutch', 'Dual Clutch')], max_length=30),
        ),
    ]
