# Generated by Django 5.1.7 on 2025-03-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(max_length=20)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('identificacion', models.CharField(max_length=30, unique=True)),
                ('licencia_conducir', models.CharField(max_length=30, unique=True)),
                ('pais_emision_licencia', models.CharField(max_length=50)),
                ('fecha_vencimiento_licencia', models.DateField()),
                ('fotos_licencia', models.JSONField(blank=True, default=list)),
                ('fotos_identificacion', models.JSONField(blank=True, default=list)),
                ('metodo_pago', models.CharField(max_length=20)),
                ('ultimos_4_digitos_tarjeta', models.CharField(blank=True, max_length=4, null=True)),
                ('numero_total_alquileres', models.PositiveIntegerField(default=0)),
                ('historial_vehiculos', models.JSONField(default=list)),
                ('historial_pagos', models.JSONField(default=list)),
                ('historial_multas', models.JSONField(default=list)),
                ('estado', models.CharField(max_length=30)),
                ('notas_internas', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
