# Generated by Django 5.1.7 on 2025-03-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inhabilitado', 'Inhabilitado'), ('pendiente_verificacion', 'Pendiente de verificación')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta_credito', 'Tarjeta de crédito'), ('tarjeta_debito', 'Tarjeta de débito'), ('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=30),
        ),
    ]
